name: Nightly Build

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  nightly-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Check NODE_AUTH_TOKEN
        run: |
          if [ -z "${NODE_AUTH_TOKEN}" ]; then
          echo "NODE_AUTH_TOKEN is not set"
          exit 1
          else
          echo "NODE_AUTH_TOKEN is set"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM with nightly tag
        run: npm run publish:nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
